// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bc97f252-b32e-44a7-ab92-bd11205b5691",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_KhDJmIx1f",
    "aws_user_pools_web_client_id": "3bfrbi91v57vn3caa396qkuf05",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3ibfox3jxnfpvfrx3setozur2i.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "myqsb2b-adminb027517082ad4aa3abf8ddb406963c9edevmyqs-devmyqs",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
